<?php
/**
 *  Randomised Programming Quiz System - A quiz system that develops random programming questions from defined templates
 *  Copyright (C) 2010-2012 Ben Evans <ben@nebev.net>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

	// For compatibility and migration to Zend
	$vQuiz = $this->quiz;
	$mQuestionAttempt = $this->question_attempt;
	$mFinished = $this->finished;
	$mMarking = $this->marking;
	$mQuizAttempt = $this->mQuizAttempt;
	$vTotalQuestions = $this->vTotalQuestions;
?>

<form action="" method="POST">
	<h2>Quiz: <?php echo $vQuiz->getQuiz_name(); ?></h2>
	<input type="hidden" name="quiz" value="<?php echo $vQuiz->getID(); ?>" />

<?php

	//Look at the quiz type - that determines what sort of display we have
	if(isset($mQuestionAttempt) && $mQuestionAttempt!=null){
	    $vType = strtolower($mQuestionAttempt->getQuestion_base()->getType());
	}
	
	if($mMarking){
	    // MARKING
	    echo $this->partial('shell/marking.phtml', array('type'=>$vType, 'questionAttempt'=>$mQuestionAttempt));
		}
	elseif($mFinished){
	    // QUIZ IS FINISHED
	    echo $this->partial('shell/quiz-finished.phtml', array('quiz'=>$vQuiz, 'quizAttempt'=>$mQuizAttempt, 'total_questions'=>$vTotalQuestions));
		}
	else{
	    // QUESTION DISPLAY
	    echo $this->partial('shell/question.phtml', array('type'=>$vType, 'questionAttempt'=>$mQuestionAttempt));
		}
	?>
</form>
	