<?php
/**
 *  Randomised Programming Quiz System - A quiz system that develops random programming questions from defined templates
 *  Copyright (C) 2010-2012 Ben Evans <ben@nebev.net>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$vAvailable = $this->available;

?>

<p>If you believe you should have more quizzes accessible to you, please contact your unit convener.</p>

<?php if (sizeof($vAvailable)==0):?>

	<p>There are no quizzes available at this time</p>
	
<?php else: ?>	
	
		<table>
		<tr><th>Quiz Title</th><th>To be completed by</th><th>Status</th><th>Best Mark</th><th>Actions</th></tr>
	<?php
		foreach($vAvailable as $vQuiz){
			echo "\t<tr>\n";
		
			echo "\t\t<td>".$vQuiz->getQuiz_name()."</td>\n";
			echo "\t\t<td>".date("d/m/Y",$vQuiz->getClose_date())."</td>\n";

			/*	So find out what status the quiz is in - Completed(1), Not completed(2) or In progress(3) (Optionally Late) */
			
			if ($vQuiz->hasPendingPrerequisite($this->username)){
				$vQuizStatus = Model_Quiz_Quiz::PREREQUISITE_PENDING;
				echo "\t\t<td>Prerequisite pending</td>\n";
			}
			else {
				$vQuizStatus = handleCurrentPosition($vQuiz, $this->username);				
			}
			
			
			
		
		
		
			/*	Marks (If completed) */
			if($vQuizStatus==Model_Quiz_Quiz::QUIZ_COMPLETED){
				$vHighest = Model_Quiz_QuizAttempt::getHighestMarkQuiz($this->username, $vQuiz);
				echo "\t\t<td>".$vHighest->getTotal_score();
				//Did they pass/fail?
				if(($vHighest->getTotal_score()/$vQuiz->getTotalQuestions())*100 >= $vQuiz->getPercentage_pass()){
					echo " (<span class='green'>PASS</span>)";
				}else{
					echo " (<span class='red'>FAIL</span>)";
				}
				echo "</td>\n";
			}else{
				echo "\t\t<td>N/A</td>\n";
			}
				
		

			/*	Possible Actions */
			if ($vQuizStatus == Model_Quiz_Quiz::PREREQUISITE_PENDING){
				echo "\t\t<td class='pending'>N/A</td>\n";
			}
			else if ($vQuizStatus == Model_Quiz_Quiz::QUIZ_AVAILABLE){
				echo "\t\t<td><a href='". $this->baseUrl() ."/shell/attempt?quiz=".$vQuiz->getID()."' target='blank'>Start Quiz</a></td>\n";
			}else if ( $vQuizStatus == Model_Quiz_Quiz::QUIZ_INPROGRESS){
				echo "\t\t<td><a href='". $this->baseUrl() ."/shell/attempt?quiz=".$vQuiz->getID()."' target='blank'>Continue Quiz</a></td>\n";
			}else{
				
				//Completed. Can we re-attempt?
				$vAttempts = Model_Quiz_QuizAttempt::getAllFromUser($this->username, $vQuiz);
				if(sizeof($vAttempts)>=$vQuiz->getMax_attempts()){
					echo "\t\t<td>N/A</td>\n";
				}else{
					//Providing it's not overdue
					if($vQuiz->getClose_date() < strtotime("now"))
						echo "<td>Quiz Closed</td>";
					else
						echo "\t\t<td><a href='". $this->baseUrl() ."/shell/attempt?quiz=".$vQuiz->getID()."' target='blank'>Attempt Again</a></td>\n";
				}			
			}
		
			echo "\t</tr>\n";
		}
		echo "</table>\n";
		?>		
<?php endif; ?>
	
<?php 

function handleCurrentPosition($vQuiz, $username){
	$vQuizAttempt = Model_Quiz_QuizAttempt::fromQuizAndUser($vQuiz, $username);
	if($vQuizAttempt != null){

		/*	So we might have started or finished the quiz */
		if ($vQuizAttempt->getDate_finished()==null){
			$vQuizStatus = Model_Quiz_Quiz::QUIZ_INPROGRESS;
			if($vQuiz->getClose_date() < strtotime("now")){
				echo "\t\t<td>In Progress (Late)</td>\n";
			}
			else{
				echo "\t\t<td>In Progress</td>\n";
			}

		}else{
			$vQuizStatus = Model_Quiz_Quiz::QUIZ_COMPLETED;
			echo "\t\t<td>Completed</td>\n";
		}
	}else{
		//No existing quiz attempt
		$vQuizStatus = Model_Quiz_Quiz::QUIZ_AVAILABLE;
		$status_msg = 'Not Completed';
		if ($vQuiz->getClose_date() < strtotime("now"))
			$status_msg .= " (Late)";

		echo "\t\t<td>$status_msg</td>\n";
	}
	return $vQuizStatus;
}

?>	