<?php $seq = $this->seq;?>
<h2>Add quizzes to Sequence: <?php echo $seq->name ?></h2>


<table class="editor_table">
<tr>
	<td class="col1"><h3>Available Quizzes</h3></td>
	<td class="col2"></td>
	<td class="col3"><h3>Quizzes in Sequence</h3></td>
	<td class="col4"></td>
</tr>
<tr>
	<td>
		<?php echo Form_Builder::select_tag('available', 
				Form_Builder::options_for_select($this->available)
				, array('multiple'=> 'multiple', 'class'=>'seq-items')
		);?>
	</td>
	
	<td class="control_buttons">
	<button id="add_btn">Add &gt;&gt;</button><br/>
	<button id="remove_btn">Remove &lt;&lt;</button>
	</td>
	
	<td>
		<?php echo Form_Builder::select_tag('current', 
				Form_Builder::options_for_select($this->current)
				, array('multiple'=> 'multiple', 'class'=>'seq-items')
		);?>
	</td>
	
	<td align="left" class="position_buttons">
	<button id="up_btn">Up</button><br/>
	<button id="down_btn">Down</button>
	</td>
</tr>
</table>
<button id="save_btn">Save</button>
<script src="<?php echo $this->baseUrl(); ?>/js/sequence-editor.js" type="text/javascript"></script>