<?php
/**
 *  Randomised Programming Quiz System - A quiz system that develops random programming questions from defined templates
 *  Copyright (C) 2010-2012 Ben Evans <ben@nebev.net>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?><!DOCTYPE html>
<html lang="en">
  <head>
    <title>Question Template Editor</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/assets/css/bootstrap.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/assets/js/highlight/styles/idea.css">
	
	<script src="<?php echo $this->baseUrl(); ?>/js/jquery-1.11.2.min.js"></script>
	<script src="<?php echo $this->baseUrl(); ?>/assets/js/highlight/highlight.pack.js"></script>
	
	<style type="text/css" media="screen">
    #editor {
        height: 525px;
    	/*white-space: pre-wrap;*/
    	word-break: break-all;
    	/*word-wrap: break-word;*/
    }
  </style>
	
	
	
	<!-- 
	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/js/cm/lib/codemirror.css">
	<script src="<?php echo $this->baseUrl(); ?>/js/cm/lib/codemirror-compressed.js"></script>
	<script>
		$(function() {
		  var problem = document.getElementById('problem');
			window.editor = CodeMirror.fromTextArea(problem, {
					mode: 'java',
					
				});
			  
		});
	</script>
	-->
	
  </head>

<body>
	
	<div class="container">
	
	<!-- Header -->
	<div class="row">
    	<div class="col-lg-12">
        	<div class="page-header">
            	<h1 id="type">Question Template Editor</h1>
          </div>
       	</div>
    </div>


	<!-- The Selection Form -->
	<div class="row">
    	<div class="col-lg-12">
			<h3>Select an XML File to Test</h3>
        	<div class="well">

				<form action="" method="GET">
					<select name="q">	
				<?php
						foreach( $this->available_selects as $ae ) {
							echo $ae;
						}
				?>
					</select>
					<input type="submit" value="Change" />
				</form>
          </div>
       	</div>
    </div>
	
	
	
	<div id="editor">
	<form>
	  <div class="form-group">
	    <label for="type">Type</label>
	    <?php echo Form_Builder::select_tag('type', 
	    		Form_Builder::options_for_select(array(
	    				'output' => 'Output',
	    				'fill-in' => 'Fill in',
	    				'multiple'=> 'Multiple'
	    				)),
	    		array('class'=>'form-control')
	    		);?>
	  </div>
	  
	  <div class="form-group">
	    <label for="time">Estimated Time</label>
	    <?php echo Form_Builder::input_tag('time', '', array('class'=>'form-control'))?>
	  </div>
	  
	  <div class="form-group">
	    <label for="concept">Concept(s)</label>
	    <?php echo Form_Builder::input_tag('concepts', '', array('class'=>'form-control'))?>
	  </div>
	  
	  <div class="form-group">
	    <label for="difficulty">Difficulty</label>
	    <?php echo Form_Builder::select_tag('"difficulty"', 
	    		Form_Builder::options_for_select(array(
	    				'1' => '1',
	    				'2' => '2',
	    				'3'=> '3'
	    				)),
	    		array('class'=>'form-control')
	    		);?>
	  </div>
	  
	  <div class="form-group">
	    <label for="instructions">Instructions</label>
	    <textarea class="form-control" rows="3" name="instructions"></textarea>
	  </div>
	  
	  <div class="form-group">
	    <label for=problem>Problem</label>
	    <?php /*
	    <textarea class="form-control" rows="12" name="problem" id="problem"></textarea>
	    */ ?>
	    <pre id="problem" style="position: relative; height:500px">
	    
	    
	    ad
	    
	    
	    asd
	    
	    
	    
	    asdf
	    
	    
	    
	    asdf
	    
	    
	    asdf
	    
	    
	    </pre>
	  </div>
	  
	  
	  

	  <button type="submit" class="btn btn-default">Submit</button>
	</form>
	</div>
	
	

	</div><!-- End Container -->
	
	<script src="<?php echo $this->baseUrl(); ?>/js/ace/ace.js"></script>
	<script>
    var editor = ace.edit("problem");
    editor.setTheme("ace/theme/twilight");
    editor.getSession().setMode("ace/mode/java");
	</script>
	
</body>
</html>