<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Question Template Editor</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/assets/css/bootstrap.min.css">
	<script src="<?php echo $this->baseUrl(); ?>/js/jquery-1.11.2.min.js"></script>
	
	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/js/ui/jquery-ui.css">
	<script src="<?php echo $this->baseUrl(); ?>/js/ui/jquery-ui.min.js"></script>
	 
	<style type="text/css" media="screen">
    #editor {
        height: 525px;
    	word-break: break-all;
    }
  </style>
	
  </head>

<body>
	
	<div class="container">
	
	<!-- Header -->
	<div class="row">
    	<div class="col-lg-12">
        	<div class="page-header">
            	<h1 id="type">Question Template Editor</h1>
          </div>
       	</div>
    </div>
    
    <?php echo Form_Builder::hidden_tag('base_url', $this->baseUrl()); ?>


	<!-- The Selection Form -->
	<div class="row">
    	<div class="col-lg-12">
			<h3>Select an XML File to Test</h3>
        	<div class="well">

				<form action="" method="GET">
					<select name="q">	
				<?php
						foreach( $this->available_selects as $ae ) {
							echo $ae;
						}
				?>
					</select>
					<input type="submit" value="Change" />
				</form>
          </div>
       	</div>
    </div>
	
	
	
	<div id="editor">
	<form id="editor-form">
	
	<div class="form-group">
	    <label for="filename">Filename</label>
	    <?php echo Form_Builder::input_tag('filename', '', array('class'=>'form-control'))?>
	  </div>
	
	  <div class="form-group">
	    <label for="type">Type</label>
	    <?php echo Form_Builder::select_tag('type', 
	    		Form_Builder::options_for_select(array(
	    				'output' => 'Output',
	    				'fill-in' => 'Fill in',
	    				'multiple'=> 'Multiple'
	    				)),
	    		array('class'=>'form-control')
	    		);?>
	  </div>
	  
	  <div class="form-group">
	    <label for="time">Estimated Time</label>
	    <?php echo Form_Builder::input_tag('time', '', array('class'=>'form-control'))?>
	  </div>
	  
	  <div class="form-group">
	    <label for="concept">Concept(s)</label>
	    <?php echo Form_Builder::input_tag('concepts', '', array('class'=>'form-control'))?>
	  </div>
	  
	  <div class="form-group">
	    <label for="difficulty">Difficulty</label>
	    <?php echo Form_Builder::select_tag("difficulty", 
	    		Form_Builder::options_for_select(array(
	    				'1' => '1',
	    				'2' => '2',
	    				'3'=> '3'
	    				)),
	    		array('class'=>'form-control')
	    		);?>
	  </div>
	  
	  <div class="form-group">
	    <label for="instructions">Instructions</label>
	    <textarea class="form-control" rows="3" name="instructions"></textarea>
	  </div>
	  
	  <div class="form-group">
	    <label for=problem>Problem</label>
	    <pre id="problem" style="position: relative; width:600px; height:500px">
	    </pre>
	  </div>
	  
	  
	  

	  <button type="submit" class="btn btn-default">Save</button>
	</form>
	</div>
	
	

	</div><!-- End Container -->
	
	
	<script src="<?php echo $this->baseUrl(); ?>/js/ace/ace.js"></script>
	<script src="<?php echo $this->baseUrl(); ?>/js/editor.js"></script>
</body>
</html>