<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Question Template Editor</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/assets/css/bootstrap.min.css">
	<script src="<?php echo $this->baseUrl(); ?>/js/jquery-1.11.2.min.js"></script>

	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/js/ui/jquery-ui.css">
	<script src="<?php echo $this->baseUrl(); ?>/js/ui/jquery-ui.min.js"></script>

	<script src="<?php echo $this->baseUrl(); ?>/js/mustache.js"></script>

	<style type="text/css" media="screen">
    #editor {
        height: 525px;
    	word-break: break-all;
    }

    /* Bootstrap override */
    .form-control {
    	font-size: 12px;
    	padding: 0px 2px;
    	height:30px;
    }

    .page-header{
    	margin:0;
    	padding: 0;
    }

    .page-header h1{
    	font-size: 16px;
    }

    .substitutions button{
    	font-size:12px;
    }

    .substitutions tr{
    	margin: 10px;
    }

    .bottom-bar button{
    	margin: 2px;
    }

    .bottom-bar{
    	margin-bottom:50px;
    }

  </style>

  </head>

<body>

	<div class="container">

	<!-- Header -->
	<div class="row">
    	<div class="col-lg-12">
        	<div class="page-header">
		          <button class="btn btn-primary back">Back to Start</button>
            	<h1 id="type">Question Template Editor</h1>
          </div>
       	</div>
    </div>

    <?php echo Form_Builder::hidden_tag('base_url', $this->baseUrl()); ?>


	<!-- The Selection Form -->
	<!--
	<div class="row">
    	<div class="col-lg-12">
			<h3>Select an XML File to Test</h3>
        	<div class="well">

				<form action="" method="GET">
					<select name="q">
				<?php
						//foreach( $this->available_selects as $ae ) {
						//	echo $ae;
						//}
				?>
					</select>
					<input type="submit" value="Change" />
				</form>
          </div>
       	</div>
    </div>
	-->
	<form action="" method="GET" class="form-inline">
		<div class="form-group">
		<label for="q">Existing files</label>
		<?php echo Form_Builder::select_tag('q', Form_Builder::options_for_select($this->available_files, $this->selected_xml), array('class'=>'form-control'));?>
		</div>
		<div class="form-group">
		<input type="submit" value="Open" class="btn"/>
		</div>
	</form>


	<div id="editor">
	<form id="editor-form" class="form-inline">

	  <div class="form-group">
	    <label for="filename">Filename</label>
	    <?php echo Form_Builder::input_tag('filename', '', array('class'=>'form-control'))?>
	  </div>

	  <div class="form-group">
	    <label for="type">Type</label>
	    <?php echo Form_Builder::select_tag('type',
	    		Form_Builder::options_for_select(array(
	    				'output' => 'Output',
	    				'fill-in' => 'Fill in',
	    				'multiple'=> 'Multiple'
	    				), $this->question->getType() ),
	    		array('class'=>'form-control')
	    		);?>
	  </div>

	  <div class="form-group">
	    <label for="time">Estimated Time</label>
	    <?php echo Form_Builder::input_tag('time'
	    		, $this->question->getEstimatedTime()
	    		, array('class'=>'form-control'))?>
	  </div>

	  <div class="form-group">
	    <label for="concept">Concept(s)</label>
	    <?php echo Form_Builder::input_tag('concepts'
	    		, implode( $this->question->getConcepts(), ',' )
	    		, array('class'=>'form-control'))?>
	  </div>

	  <div class="form-group">
	    <label for="difficulty">Difficulty</label>
	    <?php echo Form_Builder::select_tag("difficulty",
	    		Form_Builder::options_for_select(array(
	    				'1' => '1',
	    				'2' => '2',
	    				'3'=> '3'
	    				),
	    				$this->question->getDifficulty()
	    				),
	    		array('class'=>'form-control')
	    		);?>
	  </div>

	  <div class="form-group">
	    <label for="instructions">Instructions</label>
	    <textarea class="form-control" rows="3" name="instructions"><?php echo $this->question->getInstructions()?></textarea>
	  </div>

	  <table>
	  	<tr>
	  		<td width="83%">
	        <?php echo Form_Builder::select_tag('fontsize', Form_Builder::options_for_select($this->fontSizes, "12px")); ?>
	        <?php echo $this->partial('question-template-editor/themes.phtml')?>
        	</td>
        	<td></td>
	  	</tr>

	  	<tr>
		  	<td>



			  <div class="form-group">
			    <label for=problem>Problem</label>
			    <pre id="problem" style="position: relative; width:800px; height:500px"><?php echo $this->question->getProblem();?></pre>
			  </div>

			  <div class="bottom-bar">
				  <button class="btn btn-primary save">Save</button>
		      <button class="btn btn-primary back">Back to Start</button>
				  <button class="btn btn-default quality pull-right">Quality Report</button>
				  <button class="btn btn-default test pull-right">Test</button>
		  	  </div>
		  </td>
		  <td valign="top">
		  	  <br>
			  <!-- Substitutions -->
			  <p><b>Substitutions</b><button class="s_new">Add new</button></p>
			  <table class="substitutions"></table>

		  </td>
	  </tr>
	  </table>


	</form>
	</div>

	<div class="bottom"></div>



	</div><!-- End Container -->


	<script src="<?php echo $this->baseUrl(); ?>/js/ace/ace.js"></script>
	<script src="<?php echo $this->baseUrl(); ?>/js/editor.js"></script>

<script id="s_row" type="x-tmpl-mustache">
		<tr data-id="{{name}}">
	  		<td valign="top">
	  		<?php echo Form_Builder::input_tag('s[{{pos}}][name]', '{{name}}', array('class'=>'s_name'))?><br/>
	  		<button class="s_insert">Insert</button>
			<button class="s_delete">Delete</button>
	  		</td>
	  		<td>
	  		<textarea rows="2" name="s[{{pos}}][value]" class="s_value" placeholder="Enter value or PHP code">{{value}}</textarea>
	  		</td>
	  	</tr>
</script>

<script id="s_new_tpl" type="x-tmpl-mustache">
	<div title="New Substitution">
	Name: <?php echo Form_Builder::input_tag('s_name_new', '{{name}}'); ?>
	</div>
</script>
<script>
	var subs = <?php echo $this->substitutions;  ?>
</script>
</body>
</html>
